// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytqruetuadthefyclmiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cXJ1ZXR1YWR0aGVmeWNsbWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTg5OTIsImV4cCI6MjA2ODAzNDk5Mn0.aQ0KUyHmrm_mcZkMDT2QiOGH6dPfhH4tjbPZcH40IDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});